name: Test and Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: testdb
      DB_PORT: 3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # o '20' se preferisci

      - name: Install dependencies
        run: npm ci

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h "$DB_HOST" --silent; then
              echo "MySQL is up"
              break
            fi
            echo "Waiting for MySQL ($i)..."
            sleep 5
          done

      - name: Initialize test database (optional)
        run: |
          mysql -h $DB_HOST -u$DB_USER -p$DB_PASSWORD $DB_NAME < ./scripts/schema.sql
        # Check file ./scripts/schema.sql con CREATE TABLE ecc.

      - name: Run tests and collect coverage
        run: npm test -- --coverage

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
